"""
Terms of Use - Legal terms and conditions for system usage
"""

TERMS_OF_USE = """
# LEGAL LLM SUPREME COURT SYSTEM - TERMS OF USE

**Last Updated**: 2024
**Version**: 1.0

## 1. ACCEPTANCE OF TERMS

By accessing or using the Legal LLM Supreme Court System ("the System"), you agree to be bound by these Terms of Use. If you do not agree to these terms, do not use the System.

## 2. RESEARCH AND ACADEMIC USE ONLY

**IMPORTANT**: This System is designed exclusively for research and academic purposes. It is NOT intended for:
- Actual legal proceedings or litigation
- Professional legal advice or consultation
- Making binding legal decisions
- Replacing qualified legal counsel

## 3. AI-GENERATED CONTENT DISCLAIMER

### 3.1 Nature of Content
All predictions, opinions, and analyses generated by this System are produced by artificial intelligence and machine learning models. They are:
- **NOT legal advice**
- **NOT authoritative legal opinions**
- **NOT suitable for citation in legal proceedings**
- **NOT reviewed by licensed attorneys**

### 3.2 Accuracy and Reliability
While the System uses advanced AI technology and is trained on Supreme Court case law from 2022-2023:
- Predictions may be inaccurate or incomplete
- Generated opinions may contain errors or inconsistencies
- Search results may miss relevant cases
- The System cannot account for recent legal developments

### 3.3 No Warranty
THE SYSTEM IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.

## 4. PROHIBITED USES

You may NOT use the System for:
- Providing legal services to third parties
- Making decisions in actual legal cases
- Submitting AI-generated content to courts
- Circumventing the need for qualified legal counsel
- Any commercial legal practice
- Any purpose that violates applicable laws or regulations

## 5. USER RESPONSIBILITIES

### 5.1 Verification
Users must:
- Independently verify all information provided by the System
- Consult qualified legal professionals for actual legal matters
- Not rely solely on System outputs for any legal decision

### 5.2 Ethical Use
Users must:
- Use the System ethically and responsibly
- Not attempt to manipulate or misuse the System
- Respect intellectual property rights
- Comply with all applicable laws and regulations

## 6. DATA AND PRIVACY

### 6.1 Audit Logging
The System logs all queries and outputs for:
- Quality assurance and improvement
- Ethical compliance monitoring
- Research purposes
- System security

### 6.2 Data Retention
Audit logs are retained for 90 days and then automatically deleted.

### 6.3 No Personal Legal Advice
Do not submit confidential or privileged information to the System. The System does not provide personalized legal advice.

## 7. INTELLECTUAL PROPERTY

### 7.1 System Ownership
The System, including all software, models, and documentation, is proprietary.

### 7.2 Generated Content
AI-generated content is provided for research purposes only. Users may use generated content for academic research but must:
- Clearly label content as AI-generated
- Include appropriate disclaimers
- Not present content as authoritative legal analysis

### 7.3 Case Law Data
The System uses publicly available Supreme Court case law. Original case law remains in the public domain.

## 8. LIMITATION OF LIABILITY

TO THE MAXIMUM EXTENT PERMITTED BY LAW:
- The System providers shall not be liable for any damages arising from use of the System
- Users assume all risks associated with System use
- No liability for inaccurate predictions or generated content
- No liability for decisions made based on System outputs

## 9. INDEMNIFICATION

Users agree to indemnify and hold harmless the System providers from any claims, damages, or expenses arising from:
- User's use or misuse of the System
- User's violation of these Terms
- User's violation of any applicable laws

## 10. MODIFICATIONS TO TERMS

These Terms may be updated at any time. Continued use of the System after changes constitutes acceptance of modified Terms.

## 11. GOVERNING LAW

These Terms are governed by applicable laws. Any disputes shall be resolved in accordance with such laws.

## 12. CONTACT AND SUPPORT

For questions about these Terms or the System:
- This is a research system
- Contact your institution's research office
- Consult qualified legal counsel for legal matters

## 13. ACKNOWLEDGMENT

BY USING THIS SYSTEM, YOU ACKNOWLEDGE THAT:
- You have read and understood these Terms
- You agree to use the System only for research and academic purposes
- You will not rely on System outputs for actual legal matters
- You will consult qualified legal professionals for legal advice
- You understand the limitations and risks of AI-generated content

---

**REMEMBER**: This System is a research tool, not a substitute for qualified legal counsel. Always consult licensed attorneys for actual legal matters.
"""


DISCLAIMER_SHORT = """
⚠️ DISCLAIMER: This content is AI-generated for research and academic purposes only.
It does not constitute legal advice and should not be relied upon for actual legal proceedings.
Always consult qualified legal professionals for legal matters.
"""


DISCLAIMER_PREDICTION = """
⚠️ PREDICTION DISCLAIMER:
This outcome prediction is generated by artificial intelligence based on historical case patterns.
It is NOT a guarantee of actual case outcomes and should NOT be used for:
- Making legal decisions
- Advising clients
- Litigation strategy
- Any purpose requiring professional legal judgment

For actual legal matters, consult qualified legal counsel.
"""


DISCLAIMER_OPINION = """
⚠️ OPINION DISCLAIMER:
This judicial opinion is AI-generated using Retrieval-Augmented Generation (RAG).
It is NOT an official court opinion and should NOT be:
- Cited in legal proceedings
- Presented as authoritative legal analysis
- Used as a substitute for actual case law research
- Relied upon for legal advice

This is a research tool demonstrating AI capabilities in legal text generation.
For actual legal research, consult official court opinions and qualified legal professionals.
"""


def get_terms_of_use() -> str:
    """Get the full terms of use text."""
    return TERMS_OF_USE


def get_disclaimer(content_type: str = "general") -> str:
    """
    Get appropriate disclaimer for content type.
    
    Args:
        content_type: Type of content (general, prediction, opinion)
    
    Returns:
        Disclaimer text
    """
    disclaimers = {
        "general": DISCLAIMER_SHORT,
        "prediction": DISCLAIMER_PREDICTION,
        "opinion": DISCLAIMER_OPINION
    }
    
    return disclaimers.get(content_type, DISCLAIMER_SHORT)


def format_with_disclaimer(content: str, content_type: str = "general") -> str:
    """
    Format content with appropriate disclaimer.
    
    Args:
        content: Content to format
        content_type: Type of content
    
    Returns:
        Content with disclaimer appended
    """
    disclaimer = get_disclaimer(content_type)
    return f"{content}\n\n{disclaimer}"
